### ISSUE TITLE
Overlaying blocks in Pages "Bakerloo Testnet" and "Piccadilly Testnet"

### ISSUE THREAD

**Issue by jfaiza** [autonity/docs.autonity.org#180]
The "right margin sidebar" and the "main block" overlap in pages "Bakerloo Testnet" and "Piccadilly Testnet".

Example of page display:

![image](https://github.com/autonity/docs.autonity.org/assets/79405564/d8ec1154-dfca-49e3-9d84-3798b5f58039)

**Comment by jay-cousins** [comment]
Thank you for raising this @jfaiza 

@dweng0 - is this a bug or intended behaviour?

(I would have thought it was intended as the data being overlapped doesn't have a break so is non-collapsible.  Therefore, the correct behaviour is to show the ToC above the non-collapsible data on scrolling so that the ToC can still be used to navigate on the page.)

**Comment by aiman** [comment]
Normally, all page content should wrap at the appropriate margin, include any `code` elements in the body. But in the case of tables, it seems like they are not respecting the margins and going past them.

**Comment by dweng0** [comment]
Confirming this is a bug, the code is not word breaking which is causing this behaviour

**Comment by jay-cousins** [comment]
Thanks @dweng0 - @jfaiza thank you for reporting this bug.
